name: CI/CD Pipeline

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  submodules: true
                  fetch-depth: 0

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Execute build script
              run: |
                  chmod +x ./build.sh
                  ./build.sh

            - name: Upload Build Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: build-artifact
                  path: ./build

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Download Build Artifact
              uses: actions/download-artifact@v4
              with:
                  name: build-artifact
                  path: ./artifact

            - name: Install doctl
              run: |
                  sudo snap install doctl

            - name: Authenticate DigitalOcean
              env:
                  DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
              run: |
                  doctl auth init -t $DIGITALOCEAN_ACCESS_TOKEN

            - name: Set up SSH
              uses: webfactory/ssh-agent@v0.9.0
              with:
                  ssh-private-key: ${{ secrets.SSH_KEY }}

            - name: Deploy application
              env:
                  DROPLET_ID: ${{ secrets.DROPLET_ID }}
              run: |
                  PUBLIC_IP=$(doctl compute droplet get $DROPLET_ID --format PublicIPv4 --no-header)
                  scp -o "StrictHostKeyChecking=no" ./artifact/build-artifact.zip www@$PUBLIC_IP:/home/www/deploying/build-artifact.zip
                  ssh -o "StrictHostKeyChecking=no" www@$PUBLIC_IP "
                      # Ensure installation of unzip and npm
                      command -v unzip >/dev/null 2>&1 || sudo apt-get update && sudo apt-get install -y unzip
                      command -v npm >/dev/null 2>&1 || sudo apt-get install -y npm
                      
                      # Handle deployment
                      mkdir -p /home/www/deploying
                      unzip -o -qq /home/www/deploying/build-artifact.zip -d /home/www/deploying

                      # Reload the user daemon
                      systemctl --user daemon-reload

                      # Move the build files
                      mv /home/www/deploying/build /home/www/build.new
                      rm -r /home/www/deploying
                      cd /home/www/build.new/

                      # Install dependencies
                      npm install

                      # Change run script permissions
                      chmod +x /home/www/build/run.sh

                      # Swap builds atomically
                      systemctl --user stop opengig || echo 'Service not running'
                      rm -rf /home/www/build.old
                      mv /home/www/build /home/www/build.old
                      mv /home/www/build.new /home/www/build

                      # Enable and start the service
                      systemctl --user enable --now opengig
                  "
