name: Deploy to DigitalOcean Droplet

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Install doctl
          run: |
              sudo snap install doctl

        - name: Authenticate DigitalOcean
          env:
              DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          run: |
              doctl auth init -t $DIGITALOCEAN_ACCESS_TOKEN

        - name: Set up SSH
          uses: webfactory/ssh-agent@v0.5.3
          with:
              ssh-private-key: ${{ secrets.SSH_KEY }}

        - name: Deploy application
          env:
              DROPLET_ID: ${{ secrets.DROPLET_ID }}
          run: |
              ssh -o "StrictHostKeyChecking=no" \
              root@$(doctl compute droplet get $DROPLET_ID --format PublicIPv4 --no-header) "
                  cd /root/OpenGig.org
                  git pull origin main
                  git submodule update --init --recursive
                  npm install --omit=dev
                  npm start
              "
